sudo: required # Need super user permisions
services:
  - docker # travis CI install copy of docker

before_install: # commands will execute before start test or deplay
  - docker build -t yashodperera/docker-react -f Dockerfile.dev .

script: # To run our tests
  - docker run -e CI=true yashodperera/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-448738596331"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
