sudo: required # Need super user permisions
services:
  - docker # travis CI install copy of docker

before_install: # commands will execute before start test or deplay
  - docker build -t yashodperera/docker-react -f Dockerfile.dev .

script: # To run our tests
  - docker run yashodperera/docker-react npm run test -- --coverage
